import About from "../pages/user/about";
import Contact from "../pages/user/contact";
import Wishlist from "../pages/user/wishlist";
import Login from "../pages/user/login";
import Register from "../pages/user/register";
import Shop from "../pages/user/shop";
import Basket from "../pages/user/basket";
import Detail from "../pages/user/detail";
import Home from "../pages/user/home";
